name: HelloServiceClient 
packages:
    RxSwift:
      url: https://github.com/ReactiveX/RxSwift
      minorVersion: 5.1.1
    Swinject:
      url: https://github.com/Swinject/Swinject
      minorVersion: 2.7.1
    GRPC:
      url: https://github.com/grpc/grpc-swift
      minorVersion: 1.0.0
    Lottie:
      url: https://github.com/airbnb/lottie-ios
      minorVersion: 3.1.2
    LineSDK:
      url: https://github.com/line/line-sdk-ios-swift
      minorVersion: 5.7.0
options:
  bundleIdPrefix: net.chigita
  deploymentTarget:
    iOS: "13.0"
targets:
  HelloServiceClient:
    info:
      path: helloServiceClient/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
          - CFBundleURLSchemes: [line3rdp.$(PRODUCT_BUNDLE_IDENTIFIER)]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen
        LSApplicationQueriesSchemes:
            - https
            - lineauth2
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: 
            UIWindowSceneSessionRoleApplication: 
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate

    type: application
    platform: iOS
    deploymentTarget:
      iOS: "13.0"
    sources: 
      - path: helloServiceClient
    dependencies:
      - package: RxSwift
      - package: Swinject
      - package: GRPC
      - package: Lottie
      - package: LineSDK
